##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  spring配置  ###################
spring:
  profiles:
    active: dev

server:
  port: 8092

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: D:/logs/app.log


# THYMELEAF (ThymeleafAutoConfiguration)
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    #去掉thymeleaf的严格的模板校验
    mode: LEGACYHTML5
    prefix: classpath:/page/
    suffix: .html
    excluded-view-names:
  groovy:
    template:
      cache: false
